### ISSUE TITLE
How to monitor private hosts behind firewall/NAT?

### ISSUE THREAD

**Issue by victorhooi** [Pryx/server-status#93] opened 2019-12-18 04:05 UTC
We have a few Proxmox VM clusters in various locations around the world. Each of these is behind a pfSense firewall box, which also does NAT-ing (so the VM hosts aren't accessible from the public internet).

Is there some way of still using server-status - possibly we could have a jumpbox in each cluster, which pushed status updates to the server-status service, and then if we didn't hear anything, we assume it's down. Is that possible?

**Comment by thnilsen** [comment] 2020-05-18 20:31
server-status is not a monitoring solution in its current state, and was probably not ever intended to become one. The idea behind server-status is that your helpdesk team manually create an incident in server-status once they have confirmed that you have an active incident with your servers/systems. 

While it is possible to add an api that could create incidents based on events from a 3rd party monitoring system, server-status is not there as of yet.

What you need in order to monitor your servers is a system like Nagios Core, Centreon (nagios clone - can highly recommend it), or any other capable monitoring solution. Nagios/Centreon can use an agent called NSClient/NRPE to monitor remote servers. If you have a VPN between your pfSense sites you can still reach them from a central place. If not, you would need to  enable access via NAT/firewall rules to the port for NSClient/NRPE.

**Comment by Pryx** [comment] 2020-05-22 21:38
I actually had some plans for a simple monitoring solution, but it would be something really lightweight, it is not the intended primary function. What I wanted to do earlier was webhooks for monitoring uptime... I really hope to implement some of the stuff during the summer. I will close this issue, @victorhooi if you need further clarification, please let me know

**Closed by Pryx** 2020-05-22 21:38 UTC
